"""add payments table model sync

Revision ID: d129ebf1174b
Revises: 3d77d5196130
Create Date: 2026-07-23 19:06:17.245688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd129ebf1174b'
down_revision: Union[str, Sequence[str], None] = '3d77d5196130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon_redemptions')
    op.drop_table('variant_values')
    op.drop_table('product_variant_options')
    op.drop_table('coupon_categories')
    op.drop_table('review_images')
    op.drop_table('order_status_history')
    op.drop_table('chat_messages')
    op.drop_table('chat_threads')
    op.drop_table('notifications')
    op.drop_table('product_promotions')
    op.drop_table('product_variant_images')
    op.drop_table('return_requests')
    op.drop_table('variant_types')
    op.drop_table('wishlist_items')
    op.drop_table('promotions')
    op.alter_column('addresses', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.drop_constraint(op.f('uq_cart_variant'), 'cart_items', type_='unique')
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.drop_constraint(op.f('fk_cart_items_product_variant'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['product_variant_id'], ['id'])
    op.drop_constraint(op.f('carts_guest_token_key'), 'carts', type_='unique')
    op.create_index(op.f('ix_carts_guest_token'), 'carts', ['guest_token'], unique=True)
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.drop_constraint(op.f('coupons_code_key'), 'coupons', type_='unique')
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.drop_column('order_items', 'tax_amount')
    op.drop_column('order_items', 'discount_amount')
    op.add_column('orders', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('customer_name', sa.String(length=100), nullable=True))
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_orders_coupon'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_billing_address'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_shipping_address'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_customer'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customer_profiles', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'coupon_id')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'placed_at')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'shipping_amount')
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'billing_address_id')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'guest_phone')
    op.drop_column('orders', 'guest_email')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_column('orders', 'guest_name')
    op.add_column('payments', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('payments_order_id_key'), 'payments', type_='unique')
    op.drop_constraint(op.f('payments_transaction_reference_key'), 'payments', type_='unique')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'payment_status')
    op.drop_column('payments', 'transaction_reference')
    op.drop_column('payments', 'payment_provider')
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.add_column('payments', sa.Column('payment_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('transaction_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_unique_constraint(op.f('payments_transaction_reference_key'), 'payments', ['transaction_reference'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('payments_order_id_key'), 'payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'stripe_payment_intent_id')
    op.drop_column('payments', 'provider')
    op.add_column('orders', sa.Column('guest_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('guest_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('guest_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('billing_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('order_status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('placed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_customer'), 'orders', 'customer_profiles', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_orders_shipping_address'), 'orders', 'addresses', ['shipping_address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_orders_billing_address'), 'orders', 'addresses', ['billing_address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_orders_coupon'), 'orders', 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'created_by_user_id')
    op.add_column('order_items', sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.create_unique_constraint(op.f('coupons_code_key'), 'coupons', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_guest_token'), table_name='carts')
    op.create_unique_constraint(op.f('carts_guest_token_key'), 'carts', ['guest_token'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cart_items_product_variant'), 'cart_items', 'product_variants', ['product_variant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.create_unique_constraint(op.f('uq_cart_variant'), 'cart_items', ['cart_id', 'product_variant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.alter_column('addresses', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('promotions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("discount_type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying]::text[])", name=op.f('promotions_discount_type_check')),
    sa.CheckConstraint('discount_value >= 0::numeric', name=op.f('promotions_discount_value_check')),
    sa.CheckConstraint('end_date > start_date', name=op.f('chk_promotion_dates')),
    sa.PrimaryKeyConstraint('id', name=op.f('promotions_pkey'))
    )
    op.create_table('wishlist_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('fk_wishlist_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_wishlist_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wishlist_items_pkey')),
    sa.UniqueConstraint('customer_id', 'product_id', name=op.f('uq_customer_product_wishlist'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('variant_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('variant_types_pkey'))
    )
    op.create_table('return_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('refund_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'received'::character varying, 'refunded'::character varying, 'completed'::character varying]::text[])", name=op.f('return_requests_status_check')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('fk_return_requests_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_return_requests_order_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('return_requests_pkey'))
    )
    op.create_table('product_variant_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('fk_product_variant_images_variant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_variant_images_pkey'))
    )
    op.create_table('product_promotions',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('promotion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_promotions_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], name=op.f('fk_product_promotions_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'promotion_id', name=op.f('product_promotions_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("notification_type::text = ANY (ARRAY['order'::character varying, 'payment'::character varying, 'promotion'::character varying, 'coupon'::character varying, 'system'::character varying, 'account'::character varying]::text[])", name=op.f('notifications_notification_type_check')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('fk_notifications_customer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest_token', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('assigned_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['open'::character varying, 'assigned'::character varying, 'closed'::character varying]::text[])", name=op.f('chat_threads_status_check')),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], name=op.f('fk_chat_threads_agent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('fk_chat_threads_customer'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_threads_pkey'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attachment_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("sender_type::text = ANY (ARRAY['customer'::character varying, 'guest'::character varying, 'agent'::character varying, 'system'::character varying]::text[])", name=op.f('chat_messages_sender_type_check')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_chat_messages_sender'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_messages_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_order_status_history_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('order_status_history_pkey'))
    )
    op.create_table('review_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_images_review'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('review_images_pkey'))
    )
    op.create_table('coupon_categories',
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_coupon_categories_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_categories_coupon'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'category_id', name=op.f('coupon_categories_pkey'))
    )
    op.create_table('product_variant_options',
    sa.Column('product_variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_value_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('product_variant_options_product_variant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_value_id'], ['variant_values.id'], name=op.f('product_variant_options_variant_value_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_variant_id', 'variant_value_id', name=op.f('product_variant_options_pkey'))
    )
    op.create_table('variant_values',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['variant_type_id'], ['variant_types.id'], name=op.f('fk_variant_values_variant_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('variant_values_pkey'))
    )
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('redeemed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_redemptions_coupon'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('fk_coupon_redemptions_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_redemptions_order'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('coupon_redemptions_pkey')),
    sa.UniqueConstraint('coupon_id', 'customer_id', 'order_id', name=op.f('uq_coupon_redemption'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
