"""add_storefront_models_and_relations

Revision ID: ec78b9a97891
Revises: 
Create Date: 2026-07-14 16:40:57.480891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec78b9a97891'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop tables in strict dependency order to prevent FK errors
    op.drop_table('product_variant_options')
    op.drop_table('variant_values')
    op.drop_table('variant_types')
    op.drop_table('knex_migrations_lock')
    op.drop_table('knex_migrations')
    
    # 2. Apply index additions and structural adjustments
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.alter_column('order_items', 'product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_constraint(op.f('order_items_product_variant_id_foreign'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'product_variants', ['product_variant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_branches_id'), 'user_branches', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(op.f('users_role_id_foreign'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_foreign'), 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_user_branches_id'), table_name='user_branches')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_variant_id_foreign'), 'order_items', 'product_variants', ['product_variant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.alter_column('order_items', 'product_variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.create_table('product_variant_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_value_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], name=op.f('product_variant_options_product_variant_id_foreign'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_value_id'], ['variant_values.id'], name=op.f('product_variant_options_variant_value_id_foreign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_variant_options_pkey')),
    sa.UniqueConstraint('product_variant_id', 'variant_value_id', name=op.f('product_variant_options_product_variant_id_variant_value_id_uni'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('variant_values',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['variant_type_id'], ['variant_types.id'], name=op.f('variant_values_variant_type_id_foreign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('variant_values_pkey'))
    )
    op.create_table('knex_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('migration_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knex_migrations_pkey'))
    )
    op.create_table('variant_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('variant_types_pkey')),
    sa.UniqueConstraint('type_name', name=op.f('variant_types_type_name_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('knex_migrations_lock',
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_locked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('index', name=op.f('knex_migrations_lock_pkey'))
    )
    # ### end Alembic commands ###